---
$schemaver: '2.0'
deployables:
  - name: cars-tutorial
    type: Server App
    aliases:
    short_description: Tutorial for creating an API following the University API standard
    assignment_group: gro:AD-ERP Applications
    notes:
    maintained_by:
      - brettbeatty
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: google.com
        source_repo_url: https://github.com/test-ndpete-org/cars-tutorial
        swagger_urls:
          - yo.swagga.com
    microservice: true
    technologies_used:
    stages:
        production:
            urls:
                product_page:
                physical_url:
                virtual_url: google.com
            hosting_location: Other
            aws_account: <one of the AWS Account CI names in the CMDB>
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: internal
        env: production
        app: cars-tutorial
        team: asdfasdf
    federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/cars-tutorial/master/.repo-meta.yml
    x-anything:
